#!/bin/bash
#SBATCH --time=00:59:59
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=4096
#SBATCH --job-name=r_collapse
#SBATCH --output=slurmlog/slurm_%A_%a.out
#SBACTH --array=1-3:1

export OMP_NUM_THREADS =${SLURM_CPUS_PER_TASK}

python main_costfun.py tmpfile_free_kt.npz ${SLURM_ARRAY_TASK_ID}
